### ISSUE TITLE
If theres more types of interactor than distinguishable colours

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#100]
then what do we do when someone asks to colour by interactor type?

**Comment by bmeldal** [comment]
Provide a message "there are too many unique proteins in this complex to provide colours"? 

Or simply not providing the option in the drop-down menu?

Thinking out loud here...

**Comment by colin-combe** [comment]
Either of those would be an improvement.

Not providing the option is probably better but as this dropdown is outside the viewer, the code to ask the number of interactors and decide whether or not to show the option would also also outside it.

Anyway, needs some work, at moment it looks like bug. A pop up message would be easy to do.

**Comment by colin-combe** [comment]
dup of #105
