### ISSUE TITLE
Experimental tags

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#11]
Show experimental tags and other features only present in IntAct experimental evidence

**Comment by colin-combe** [comment]
This functionality is required by some evidence data. Currently, we don't have issues here for all the new viewer functionality required by evidence data. Perhaps we should keep it this way and, in the short term, keep the issues here focussed on things that are problems for viewer as deployed in the Complex Portal?

If so, we could close this?
Could apply same argument to #9 and close it too.

**Comment by colin-combe** [comment]
@bmeldal FYI... a justification for closing two 'medium term' tasks assigned to me. Could keep issues here focussed on current deployment in Complex Portal?
(Maybe correct thing to do is use Milestones? but i'm looking to clean up/close things)

**Comment by bmeldal** [comment]
Was this referring to expt features in experimental data of the links from complexes to expt evidence? If it's the former, close it, if the latter, make it a milestone as that is important.

**Comment by colin-combe** [comment]
I changed the "of" to "or" in your previous comment - seems weird I can edit your comments.

Anyway, its the former - I'll close it and take this as an indication to keep the tickets here focussed on the viewers current use in the Complex Portal. 

Re. the latter, showing curated complex data alongside the supporting experimental data - this is dependant on first getting the viewer to work well with experimental evidence data.

**Comment by bmeldal** [comment]
Great. 

of/or are standard typos for me... :( Yes, strange you can edit my comment, probably because you are owner... i can edit yours.
