### ISSUE TITLE
Provide runtime options as an object.

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#31]

**Comment by colin-combe** [comment]
One possible option is whether panning the entire view by click/drag on background is enabled.

This is now disabled in current version. I don't think is was needed/useful for viewer in complex portal.

**Comment by bmeldal** [comment]
??? Don't know the bkgr to this issue.

**Comment by colin-combe** [comment]
I think this can be closed. I think what the runtime options should be and how they are passed in are more to do with the design of the bioJS wrapper ( #8 )
