### ISSUE TITLE
Create method for asynchronous loading of data.

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#32]
In addition to loading data from an existing JSON object, the displayer should have an asynchronous method to load data from a web service.

Include:
1. GET method
2. Loading message

**Comment by bmeldal** [comment]
Whatever provides the best UX! I don't know if this is still an issue.

**Comment by colin-combe** [comment]
(in my opinion) I don't think its an issue because it can fairly easily be dealt with outside of viewer. E.g. you could use the d3.json() function to asynchronously load data as follows:

				    d3.json(pathToYourData, function(data) {
						myInteractionViewer.readMIJSON(data);
					});   

I'm going to tag it 'won't fix' and close
