### ISSUE TITLE
Auto Layout does not reposition links.

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#40]
Auto Layout repositions interactors but not the links between them. 

Sample scenario:
1. Visit http://wwwdev.ebi.ac.uk/intact/complex/details/EBI-6676762
2. Drag interactor dbhb_ecoli somwhere new.
3. Click Auto Layout. *Note that links did not move with the interactor.*
4. Drag the disjointed interactor again. *Note that the link has now reconnected.*

**Comment by joshkh** [comment]
This only seems to occur for complexes where their interactors are initially rendered in bar form.

**Comment by colin-combe** [comment]
I think thats correct, Josh. It looks like the "proteins" referred to on 
lines 23 - 34 of Layout.js are missing calls to setAllLinkCoordinates() 
after they are moved.

e.g. insert:
p1.setAllLinkCoordinates();
p2.setAllLinkCoordinates();

at line 33. (untested)



-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by joshkh** [comment]
Fixed by the mentioned pull request. Thanks for the help, Colin.

**Comment by colin-combe** [comment]
Also required "protein.setAllLinkCoordinates();" to be added at line 24, to account for the case where there was only one node.

I've added it in my branch, you'll get it the next time you pull.

Also notice that the variable names in autolayout.js could be tidied up, its refering to everything as 'proteins' - a hangover from the crosslink-viewer. But there are problems with using either the word 'interactor' or 'participant' I think... can discuss later.
