### ISSUE TITLE
Problem in the hull of the complex shown when you do zoom into the sequence

### ISSUE THREAD

**Issue by maitesin** [MICommunity/interaction-viewer#45]
If you click in one of the participants of the complex the sequence is shown. Then you can use the "Shift + right click" combination to zoom into the sequence. The problem is if you after a couple of zooms you call the method resetZoom. It will move the participant back to the normal state, but the hull will not change.

**Comment by colin-combe** [comment]
Should be fixed by pull request #46. Closing.
