### ISSUE TITLE
Prevent nodes from leaving the viewbox when dragged.

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#50]

**Comment by colin-combe** [comment]
It seems no one is crying out for this at moment? Its not a big priority for me.
If Josh is now mainly working on the circular viewer / chord diagram we could just close smaller technical tasks ( this, #31 , #32  ) he has assigned to him here. 

(Could tag as 'won't fix' and re-open if/when we do want to fix).

**Comment by colin-combe** [comment]
@bmeldal FYI Birgit... a justification for closing 4 relatively minor tasks assigned to Josh here

**Comment by bmeldal** [comment]
I think this is more or less fixed. I just played with it again and when you toggle back from sequence view to little circle the element comes back into view. Of course the full sequence will rarely fit in the box so you have to drag it around anyway. I don't know if that's a recent feature upgrade from you, Colin, or something Oscar did when he added the faint frame just before he left??? I only just noticed it but I haven't been teaching for a while so haven't played with the features or made new slides...

Plus we (Oscar?) changed the reset button, so it all reset on one mouse click anyway.

**Comment by colin-combe** [comment]
OK, closing
