### ISSUE TITLE
Expose variable to reveal version number.

### ISSUE THREAD

**Issue by joshkh** [MICommunity/interaction-viewer#55]
It might be useful to have an exposed variable that reveals the build version of the complex portal:
xlv.VERSION = "1.0.0-beta"

**Comment by bmeldal** [comment]
Oh, there was a request for versioning of the CP and it was a very valid point. But that would be @tschaka1904 job and I added it to his internal work list.

Hasn't the viewer itself got some versioning control? I now @joshkh has been banging on about it from day 1 - and too right ;-)

So, yes, I think this can be closed :)

**Comment by colin-combe** [comment]
I think we're using github tags for marking versions (talking here about versions of the interaction-viewer not versions of the Complex Portal). 

Versions numbers also appear in the bower.json and package.json files associated with the build process.

I guess these version numbers (in github tags and json files for build) need to be kept in synch manually, its something to remember. Currently they look a bit out of synch - the github tag for the last release says v1.0.0-beta1, the info in the build files says 0.0.1.

Personally, I don't want to add the version number in yet another place.

I'll wait a bit to see if @joshkh has anything to add on this subject, but then I think it can be closed.

**Comment by joshkh** [comment]
Both Bower and NPM require version numbers in their configuration files (bower.json and package.json). They haven't been maintained as much during development but we should definitely stay on top of it  when version 1 becomes official so that we can release the viewer to the package managers for BioJS.

The version numbers can be incremented automatically as part of the build process. I'll work on implementing it.

**Comment by joshkh** [comment]
Revisit when build process is updated.
