### ISSUE TITLE
Some molecule types not recognised

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#59]
Some molecule types not recognised by viewer - e.g. 'small nucleolar rna'.

'small nucleolar rna' can have same symbol as other RNA. Birigt to send list of additional molecule types and which symbols to use. Will then fix.

**Comment by bmeldal** [comment]
Interactor Types not recognised:

single stranded deoxyribonucleic acid MI:0680
double stranded deoxyribonucleic acid MI:0681
small nucleolar rna MI:0609
small nuclear rna MI:0607
transfer rna MI:0325

Group all DNAs by MI:0319 (includes MI:0680 & MI:0681)
Group all RNAs by MI:0320 (includes  MI:0607 & MI:0609 & MI:0325)

The grouping should be flexible to allow more of the RNA children to be used in future complexes, esp as biologists keep finding new RNA types and we'll be adding more CV to the structure.

Any questions, just shout :)

Birgit

**Comment by colin-combe** [comment]
OK, should work for all of these now. I added in some other cv terms I could see from the ontology browser (e.g. there's about a dozen different kinds of RNA).

The code responsible for this is in a function called newMolecule (lines 442 - 514 of Controller.js) - it should be fairly readable/easy to maintain.
