### ISSUE TITLE
Explanation of colours in Legend

### ISSUE THREAD

**Issue by lutzfischer** [MICommunity/interaction-viewer#61]
The currently used color scheme should be explained in the legend

**Comment by colin-combe** [comment]
OK - dynamic legend that displays domain colours added by pull #64.
You can currently see it at interactionviewer.org.

Max - to get this functionality you will need to copy some code out of the index.html file. This code has a dependency on rgbcolor.js which is in the vendor folder. If you look at index.html you should see whats happening - a listener is registered that is notified every time legend changes. Ask if any questions.
