### ISSUE TITLE
Hiding the tool tip with style="display:none"

### ISSUE THREAD

**Issue by lutzfischer** [MICommunity/interaction-viewer#63]
Inkscape (my vector-graphics application of choice) ignores visibility=hidden - addmitetly a bug on their site. But adding  style="display:none" as attribute would produce the same result and would be correctly interpreted by inkscape as well.

**Comment by colin-combe** [comment]
thanks Lutz - fixed by pull #64.
Actually its using the display attribute of SVG elements (display= none) rather than the css attribute (style="display:none")
