### ISSUE TITLE
update UML on wiki

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#65]
TODO: update UML diagram on wiki

**Comment by colin-combe** [comment]
The UML diagram at https://github.com/MICommunity/interaction-viewer/wiki/UML has been updated to reflect changes I'm making to try to make the viewer work well with evidence data. And also just to try to simplify it and make it more maintainable. Actually, the diagram is easier to see at http://interactionviewer.org/InteractionViewer.png than on the github wiki.

Due to a mistake, the previous UML diagram isn't there for comparison (I can get it back if people want to see it) but basically the link side of things is simpler. The "BinaryLink" and "UnaryLink" object types are gone, they did serve a purpose but they also complicated things a lot. I'm going to see how we get on without them.

I'd like to close this... there is not an accurate UML diagram for whats currently being used in the Complex Portal but there is a UML that shows where things are going.

OK to close? You can ask me if you need info on structure of the viewer code.

**Comment by colin-combe** [comment]
@bmeldal FYI

**Comment by bmeldal** [comment]
I don't use the UML, @tschaka1904, do you still need this open?

**Comment by colin-combe** [comment]
I worry about the structure of the code being understandable to others and not seeming too crazy... so this is important (to me anyway).

But at the moment, I don't think Max should need to go into the internals of the code, which is what the diagram shows. I think I can close...
