### ISSUE TITLE
dependencies in package.json

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#66]
I deleted some (as far as I know) unneeded dependencies from package.json - these being: lodash, jsonview, underscore, mocha.

package.json also declares dependencies on d3.js  and colorbrewer.js. These are also reffered to in the source files (e.g. Controller.js) by statements like: require(../../../vendor/d3.js).

Is this how its meant to be? It feels wrong having it two different places.

Also, the viewer code doesn't use jquery but the build process does. Do we still need jquery and jquery.browserify in package.json?

**Comment by joshkh** [comment]
> I deleted some (as far as I know) unneeded dependencies from package.json - these being: lodash, jsonview, underscore, mocha.

Yes, none of those are needed at the moment. Mocha will probably reappear when I write tests but there's no sense in defining it if we're not yet using it.

> package.json also declares dependencies on d3.js and colorbrewer.js. These are also reffered to in the source files (e.g. Controller.js) by statements like: require(../../../vendor/d3.js).

Good catch. It looks like the dependency management needs some attention.

When possible, convention says to use bower for front-end libraries (d3, colorbrewer) and npm for node modules (browserify, grunt). The deciding factor is how well the libraries play with browserify which is something on the back of my mind for BioJS.

Looking through /vendor/ folder, here's what's available via bower:
FileSaver [https://github.com/Teleborder/FileSaver.js]
D3 [https://github.com/mbostock/d3]
ColorBrewer [https://github.com/jeanlauliac/colorbrewer/blob/master/colorbrewer.js]
RGBColor [https://github.com/ariutta/rgb-color]

I can't locate Point2D or Intersection and I think it's appropriate for them to stay in the repository if they're not source controlled.

> Also, the viewer code doesn't use jquery but the build process does. Do we still need jquery and jquery.browserify in package.json?

jQuery can be removed! At this point we won't have any dependencies in package.json. 

Are you okay with me adding bower dependencies back to the project? I can set up a branch to see how it looks before we commit to anything.

**Comment by colin-combe** [comment]
On 15/06/15 12:13, joshkh wrote:
>
> I can't locate Point2D or Intersection and I think it's appropriate 
> for them to stay in the repository if they're not source controlled.
>

Agreed.

> Are you okay with me adding bower dependencies back to the project? I 
> can set up a branch to see how it looks before we commit to anything. 

Yes, go for it,
C



-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Closing - task completed by Josh. 

(I think there is still a dependency on RGBColor that we don't need, its only used by the legend in the demo file, not the viewer itself.)
