### ISSUE TITLE
labels in legend

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#67]
The 'small molecule' label should say 'bioactive entity' as the little triangle is used to represented both small molecules and polysaccharides, right? (And anything that had 'bioactive entity' as its type.) 

The 'your complex' label in the legend should probably give the EBi accession number for the complex?

**Comment by bmeldal** [comment]
Yes, I think you are right!

Sorry, didn't see this question until now...

**Comment by colin-combe** [comment]
This is changed in the demo file for the interaction-viewer project (my branch), but not in the Complex Portal.

The code that draws the legend in the Complex Portal is not part of the interaction-viewer (though it was a cut'n'paste from the demo file). I'm gonna close this issue because (strictly speaking) I think it's outside the scope of this project.

**Comment by bmeldal** [comment]
Max @tschaka1904, I will log this in our temp bug file.

Thanks for updating your branch, Colin.

Birgit
