### ISSUE TITLE
SVG export broken in Safari

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#71]
I think you'll find this is the case...

see eligrey/FileSaver.js#12

**Comment by colin-combe** [comment]
"Fixed" by  a281b19

In fact, the fix consists of moving the actual download code outside the viewer (because the only reliable solution needs server side solution).

Now the viewer has a function called "getSVG" which return the SVG XML but does not try to  download file.

As discussed, this change creates some work for @tschaka1904 -
Max could quickly recreate the old solution, which doesn't work in Safari and can't reliably set file names, by  copying and pasting javascript from  https://github.com/MICommunity/interaction-viewer/blob/a281b1969f80cb3c016b126222d035390b6778ce/index.html#L166-L169

But the better solution (AFAIK the only one that actually works cross-browser) means you need to put the data in a hidden form then submit that form to a server which sends back the file to download.

An example of client-side javascript needed for this is:
https://github.com/colin-combe/CLMS-UI/blob/master/js/downloads.js#L40-L70
(I am using that code and it seems to work fine)
A php example for the server side 'bounce' is:
https://github.com/colin-combe/CLMS-UI/blob/master/php/download.php

@tschaka1904 - Ask me if any questions

(Getting it working properly on the Complex Portal is probably something that should be added to EBI's internal tracker... )

**Comment by bmeldal** [comment]
Thanks, Colin. I moved it to our tracker to fix CP server side.

**Comment by colin-combe** [comment]
For information, this issue with Safari may only apply to Safari on an iMac not Safari on an iPad
