### ISSUE TITLE
UniProt features need trimming. 

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#73]
Need more info on what to trim and what to leave.

**Comment by colin-combe** [comment]
Would removing annotations below a certain length do for this?

**Comment by colin-combe** [comment]
for info, from Sandra (off GH) :
>How difficult would it be to separate out the UniProt features. At the
moment we show All, which is too much especially if the protein has been
crystallised. UniProt domains would probably be the most useful default
feature to view, but I can see times, for example, when users would wish
to switch to a view which shows where variants line on the sequence. So
an on/off tick box, for example.

**Comment by colin-combe** [comment]
So... in the longer term there are several possible improvements to the way annotations are handled / shown. See also #80

In the short term (v1 release), commit  bc8f876  changes the code so that only the domains from uniprot annotations are shown (Sandra's suggested default).

Going to close... if, after testing, this doesn't seem adequate for v1 can reopen.

**Comment by bmeldal** [comment]
Thanks, Colin. Moved to our tracker to commit changes.
