### ISSUE TITLE
Superfamily Feature - change name

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#81]
Hi Colin,

Can you please change the name of the 'superfamily' feature to 'domain' as that's what's displayed. It trips me up every time I teach!

Superfamilies are classifications...

Thanks,
Birgit

**Comment by colin-combe** [comment]
If this is with reference to the Complex Portal then I think the name shown in that menu is 'on the EBI side'. 

I think Max should be able to change it - @tschaka1904

**Comment by bmeldal** [comment]
Ah, it's a bit of a black box for me as to what we add... I'll check with Max when he comes in.

**Comment by colin-combe** [comment]
I'm closing this - I'm pretty confident it's one for Max. If I'm mistaken then feel free to tell me off and reopen it.

**Comment by bmeldal** [comment]
Thanks. I've moved the ticket to our internal tracker :)
