### ISSUE TITLE
viewer introduces spurious composite binding sites

### ISSUE THREAD

**Issue by colin-combe** [MICommunity/interaction-viewer#84]
The issue on the Intact Editor at http://www.ebi.ac.uk/intact/jira/browse/EDITOR-35 is actually a bug in the viewer.

The viewer is introducing a composite binding site where there shouldn't be one.

**Comment by colin-combe** [comment]
#85 should fix this. Will wait for confirmation everything's OK before closing.

The viewer still shows a genuine composite binding site (as in EBI-10828997) correctly. 

However, the code cannot deal with a composite binding site that is across two different participants - I think its going to be v2.0.0 before that's fixed.

**Comment by bmeldal** [comment]
I think that's working now.

**Comment by colin-combe** [comment]
OK, lets try to fix #86 also before doing another release,
C

On 22/02/16 11:44, Birgit wrote:
>
> I think that's working now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MICommunity/interaction-viewer/issues/84#issuecomment-187137511>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by bmeldal** [comment]
I wasn't sure if they were linked so made it a new issue just in case.

**Comment by colin-combe** [comment]
they're not linked...

On 22/02/16 11:55, Birgit wrote:
>
> I wasn't sure if they were linked so made it a new issue just in case.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MICommunity/interaction-viewer/issues/84#issuecomment-187140837>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.
