### ISSUE TITLE
Domain doesn't display properly after toggling bar to cicle and back

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#86]
e.g. EBI-9082861
Open bar and expand at least once. Toggle back to circle and back to bar and the coloured region expands beyond the bar. I noticed this a little while ago and forgot to report it.

All goes back to normal after "reset" but error is repeated as soon as you expand the bar again.

**Comment by colin-combe** [comment]
Yes - replicated error. Clearly a problem there. Will look at it this 
week sometime.

On 22/02/16 11:49, Birgit wrote:
>
> e.g. EBI-9082861
> Open bar and expand at least once. Toggle back to circle and back to 
> bar and the coloured region expands beyond the bar. I noticed this a 
> little while ago and forgot to report it.
>
> All goes back to normal after but error is repeated as soon as you 
> expand the bar again.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/MICommunity/interaction-viewer/issues/86>.
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by colin-combe** [comment]
Should be fixed by pull request #87 (not merged yet).
You can check its working at http://interactionviewer.org
Will close issue / merge / do another release after its confirmed this is fixed.

**Comment by bmeldal** [comment]
Looks fine on demo site :) I'll add it to our tracker to update our instances.
@tschaka1904

**Comment by colin-combe** [comment]
@tschaka1904 - did this get updated in the Complex Portal site? 
I think the bug is still there, see below - to replicate the error in the complex portal you expand bar with shift-click then toggle between circle and bar) 
![screenshot from 2016-11-10 14 10 43](https://cloud.githubusercontent.com/assets/977607/20179807/ba05ba60-a74f-11e6-9fab-ef6fd1857a85.png)
