### ISSUE TITLE
'dead' highlights

### ISSUE THREAD

**Issue by bmeldal** [MICommunity/interaction-viewer#88]
We've done UX testing on 3 volunteers today and came up with 2 irritating features (related!):

a) when you click on the blue background it highlights all participants with a yellow border

b) when you click on an edge in the non-expanded version it highlights the edge and does nothing. One user got so frustrated she didn't try to click on the nodes after that!

We, (that is Sangya and I) think we should disable these 'highlight' features until they actually lead somewhere.

(We are testing a few more people this week, then we'll share all the observations.)

**Comment by colin-combe** [comment]
On 08/03/16 15:19, Birgit wrote:
>
> We, (that is Sangya and I) think we should disable these 'highlight' 
> features until they actually lead somewhere.
>

OK, will disable pointless highlighting.

> (We are testing a few more people this week, then we'll share all the 
> observations.)
>

look forward to the feedback ;)

c


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by bmeldal** [comment]
Thanks, Colin. We had another user yesterday who did the same, clicked on the edge to no avail, then didn't bother clicking on the nodes...

**Comment by colin-combe** [comment]
On 10/03/16 07:49, Birgit wrote:
> clicked on the edge to no avail, then didn't bother clicking on the 
> nodes...

OK.

It does do something - if you click and drag on an edge it moves around 
those things it is connected to. Probably not really that useful and 
sounds like it is doing more harm than good...

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by bmeldal** [comment]
Ah, not intuitive since none of us discovered this either. 
Yes, better to remove as it clearly isn't a function people jump on!

What they expect (Pablo especially!) is to see a link to the interaction evidence when clicking on an edge. Of course, that's the longterm plan :) I wish we could implement it more quickly... :(

**Comment by colin-combe** [comment]
On 11/03/16 07:46, Birgit wrote:
> What they expect (Pablo especially!) is to see a link to the 
> interaction evidence when clicking on an edge.


This is one reason why that clicking/selection functionality on the 
links is there (so as to bring up relevant evidence).

This is different (easier) than graphically overlaying the evidence on 
the curated complex (something we have also discussed).

I could easily provide the information on what has been clicked - I 
don't know how you would use this to get the relevant evidence out the 
intact database though. I think that would be something for the EBI end.

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by bmeldal** [comment]
@tschaka1904 @git4anjali 
Is this something we can work on in the near future, maybe for the testing in May?

Colin, where does the viewer grab the edge info from? The JSON or can we decide? If it's the latter I would do a PSICQUIC search for now - and opening PSICQUIC view when you click on the edge. Once we have DIP in the fold we can link to Intact or wherever/whatever we are going to all the all-inclusive DB by then. We can't link to Intact yet as some of the evidences are in DIP but not in IMEx.

**Comment by colin-combe** [comment]
The edge info is from the JSON. I think we intend to look again sometime at how we can link evidence info.

Dead highlights fixed by #89
