### ISSUE TITLE
InterMine report page - the complex is too tall

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/interaction-viewer#90]
Search for EBI-9696567

![ebi-9696567](https://cloud.githubusercontent.com/assets/1663057/14252539/c07c63b2-fa7f-11e5-9832-350be2f98c3d.png)

It's too tall. Or rather, our display area is too short.

**Comment by colin-combe** [comment]
Not sure where to find this example - could you use the developer tools in a browser to check whether the SVG element extends beyond what we see of it. E.g. its in a div thats smaller than it or something like that.

But yes, could be a bug in the viewer

**Comment by bmeldal** [comment]
It's not an issue in the CP:
http://www.ebi.ac.uk/intact/complex/details/EBI-9696567

**Comment by colin-combe** [comment]
it might be something to do with the margin or padding on one of the 
elements


On 15/04/16 13:18, Birgit wrote:
>
> It's not an issue in the CP:
> http://www.ebi.ac.uk/intact/complex/details/EBI-9696567
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/MICommunity/interaction-viewer/issues/90#issuecomment-210443027>
>


The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by julie-sullivan** [comment]
@yo fixed this.
