### ISSUE TITLE
EBI-9696567 - never stops dancing

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/interaction-viewer#92]
https://www.ebi.ac.uk/intact/complex/details/EBI-9696567

**Comment by bmeldal** [comment]
Stops for me. But it's rather big and takes a while to build.

**Comment by colin-combe** [comment]
I can increase the ''friction' on the layout algorithm so that it stops more quickly but i think this is more likely to end in a sub-optimal layout

**Comment by julie-sullivan** [comment]
Yes, @bmeldal is right (or @colin-combe fixed it!). It's a large complex and takes a few seconds to build.

Looks great!
