### ISSUE TITLE
SVG download - needs file extension

### ISSUE THREAD

**Issue by julie-sullivan** [MICommunity/interaction-viewer#96]
If I click on the SVG button, a file downloads. However I can't open that file unless I change the file extension to be *.svg. 

My filename was "pUcXkQ2H" but for @joshkh it was "download", so seems to be a browser issue. It's supposed to be named "complex-viewer.svg".

I tested on humanmine, the complex portal, and interactionviewer.org

**Comment by colin-combe** [comment]
as for #97 - file download is now outside the viewer so closing

see https://github.com/MICommunity/interaction-viewer/issues/71#issuecomment-157691145
 `could quickly recreate the old solution, which doesn't work in Safari and can't reliably set file names, by [...]`
